theme: jekyll-theme-minimal
title: R data science
description: 使用tidyverse包完成数据处理，数据可视化。这是我用来记录学习[R in action 3rd](https://livebook.manning.com/book/r-in-action-third-edition)、[R for data science](https://r4ds.hadley.nz/)、[ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)等的笔记。
