project:
  type: book
  output-dir: docs

book:
  title: "R data science_notes"
  author: "王安林"
  date: "2023/12/20"
  chapters:
    - part: "basic R"
      chapters: 
        - index.qmd
        - intro.qmd
    - part: "tidyverse R"
      chapters: 
        - summary.qmd
        - references.qmd

bibliography: references.bib

execute:
  warning: false
toc: true
toc-depth: 4
toc-location: right
number-sections: true
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
crossref: 
  fig-title: 图
  fig-prefix: 图
  
fig-width: 6
fig-asp: 0.618

format: 
  html: 
    theme: cosmo
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: katex
    

editor: visual

