project:
  type: book
  output-dir: docs

book:
  title: "R_notes"
  author: "王安林"
  date: "2023/12/20"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

